server:
  port: 8081

spring:
  data:
    mongodb:
      host:
      port: 27017
      database:
      username:
      password:
  redis:
    host:
    port: 6379
    password:
    database: 0
#  mail:
#    host: smtp.yandex.com
#    port: 465
#    protocol: smtp
#    username:
#    password:
#    # 默认的邮件编码为UTF-8
#    default-encoding: UTF-8
#    # 配置SSL 加密工厂
#    properties:
#      mail:
#        smtp:
#          auth: true
#          ssl:
#            enable: true
#          socketFactoryClass: javax.net.ssl.SSLSocketFactory
#        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
#        debug: true
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
